import { request } from "../service";

export const models = [{
  consum: -80,
  value:"V_2",
},{
  consum: -50,
  value: "V_2_TURBO"
}]
export const ratios = ["ASPECT_1_1","ASPECT_16_9","ASPECT_4_3"];
export const styles = ["GENERAL", "REALISTIC","DESIGN","RENDER_3D","ANIME"];
export const magics = ["AUTO","ON","OFF"]
export const zhCN = {
  model: "模型",
  modelV2: "高质低速",
  modelV2Desc: "生成高质量图片，生成速度较慢",
  modelV2TURBO: "低质高速",
  modelV2TURBODesc: "快速生成一张图片，图片质量可能较低",
  magic_prompt_option: "魔法补全提词",
  magicAUTO: "自动",
  magicAUTODesc: "由AI判断是否自动补全提词",
  magicON: "开启",
  magicONDesc: "开启自动补全提词，例如：在提示词中输入“猫”，自动补全为“一个可爱的猫咪”等",
  magicOFF: "关闭",
  magicOFFDesc: "关闭自动补全提词",
  aspect_ratio: "宽高比",
  ratioASPECT11: "1:1",
  ratioASPECT11Desc: "如: 300x300 800x800",
  ratioASPECT169: "16:9",
  ratioASPECT169Desc: "如: 400x225 1280x720",
  ratioASPECT43: "4:3",
  ratioASPECT43Desc: "如: 320x240 640x480",
  prompt: "提词",
  style_type: "风格",
  styleGENERAL: "通用",
  styleGENERALDesc: "由AI根据提词判断",
  styleANIME: "动漫风",
  styleANIMEDesc: "生成动漫风格的图片",
  styleRENDER3D: "3D效果",
  styleRENDER3DDesc: "生成带有3D立体感受的图片",
  styleREALISTIC: "真实感",
  styleREALISTICDesc: "生成真实画风的图片",
  styleDESIGN: "设计风",
  styleDESIGNDesc: "生成设计感较为强烈的图片",
  negative_prompt: "反向提词",
  seed: "种子",
}
export const enUS = {
  model: "Model",
  modelV2: "Quality&Slow",
  modelV2Desc: "Generate high quality images but slowly",
  modelV2TURBO: "Qucikly&LowQuality",
  modelV2TURBODesc: "Generate low quality images quickly",
  magic_prompt_option: "Magic Prompt Option",
  magicAUTO: "Auto",
  magicAUTODesc: "Determined by AI",
  magicON: "On",
  magicONDesc: `Enable automatic completion of prompts, such as entering  in the prompt and automatically completing it as "a cute cat", etc`,
  magicOFF: "Off",
  magicOFFDesc: "Close automatic completion of prompts",
  aspect_ratio: "Aspect Ratio",
  ratioASPECT11: "1:1",
  ratioASPECT11Desc: "example size: 300x300 800x800",
  ratioASPECT169: "16:9",
  ratioASPECT169Desc: "example size: 400x225 1280x720",
  ratioASPECT43: "4:3",
  ratioASPECT43Desc: "example size: 320x240 640x480",
  prompt: "Prompt",
  style_type: "Style Type",
  styleGENERAL: "General",
  styleGENERALDesc: "Generate images with general style",
  styleANIME: "Anime",
  styleANIMEDesc: "Generate images with anime style",
  styleRENDER3D: "Render3D",
  styleRENDER3DDesc: "Generate images with render3d style",
  styleREALISTIC: "Realistic",
  styleREALISTICDesc: "Generate images with realistic style",
  styleDESIGN: "Design",
  styleDESIGNDesc: "Generate images with strong design elements",
  negative_prompt: "Negative Prompt"
}
