export const zhCN = {
  "model":"模型选择",
  "fast":"快速模式",
  "fastDesc":"日常推荐使用",
  "turbo":"极速模式",
  "turboDesc":"比快速更快一点",
  "method": "功能选择",
  "imagine": "以文生图",
  "imagineDesc": "输入提词生成图片",
  "blend": "多图融合",
  "blendDesc": "选择2-5张图片进行智能融合",
  "describe": "以图生文",
  "describeDesc": "对图片进行详细的文字描述",
  "inpaint": "区域重绘",
  "inpaintDesc": "框选图片中指定区域进行智能重绘",
  "type":"生图渠道",
  "MJTT":"渠道一",
  "MJTTDesc": "",
  "MJ302": "渠道二",
  "MJ302Desc": "",
  "upsample1":"放大图一",
  "upsample2":"放大图二",
  "upsample3":"放大图三",
  "upsample4":"放大图四",
  "reroll":"整张重绘",
  "🔄":"整张重绘",
  "variation1":"重绘图一",
  "variation2":"重绘图二",
  "variation3":"重绘图三",
  "variation4":"重绘图四",
  "U1":"放大图一",
  "U2":"放大图二",
  "U3":"放大图三",
  "U4":"放大图四",
  "V1":"重绘图一",
  "V2":"重绘图二",
  "V3":"重绘图三",
  "V4":"重绘图四",
  "Custom Zoom":"自定义放大",
  "upscale_subtle":"高清扩图",
  "Upscale (Subtle)":"高清扩图",
  "redo_upscale_subtle":"再次进行-高清扩图",
  "Redo Upscale (Subtle)":"再次进行-高清扩图",
  "upscale_creative":"高清扩图",
  "Upscale (Creative)":"高清扩图",
  "redo_upscale_creative":"再次进行-高清扩图",
  "Redo Upscale (Creative)":"再次进行-高清扩图",
  "Vary (Subtle)":"微重绘",
  "Vary (Strong)":"强重绘",
  "Vary (Region)":"局部重绘",
  "low_variation":"小幅变化",
  "high_variation":"大幅变化",
  "zoom_out_2":"2倍缩小图像",
  "Zoom Out 2x":"2倍缩小图像",
  "zoom_out_1_5":"1.5倍缩小图像",
  "Zoom Out 15x":"1.5倍缩小图像",
  "pan_left":"向左平移扩展",
  "pan_right":"向右平移扩展",
  "pan_up":"向上平移扩展",
  "pan_down":"向下平移扩展",
  "❤️": "收藏",
  "⬅️":"向左平移扩展",
  "➡️":"向右平移扩展",
  "⬆️":"向上平移扩展",
  "⬇️":"向下平移扩展",
  "make_square":"正方形",
}
export const enUS = {
 
}